# SPDX-FileCopyrightText: (C) 2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

---
version: v0.1.0
logLevel: info
GUID: 'aaaaaaaa-0000-1111-2222-bbbbbbbbcccc'
manageability:
  enabled: true
  serviceURL: 'infra.test.edgeorch.intel.com:443'
  heartbeatInterval: 10s
rpsAddress: 'rps.test.edgeorch.intel.com'
statusEndpoint: 'unix:///run/node-agent/node-agent.sock'
metrics:
  enabled: true
  endpoint: 'unix:///run/platform-observability-agent/platform-observability-agent.sock'
  interval: 10s
accessTokenPath: /etc/intel_edge_node/tokens/platform-manageability-agent/access_token
